### ISSUE TITLE
Upload of Flac files

### ISSUE THREAD

**Issue by fa7ecc1f76** [amikrop/aiomixcloud#2]
Hi there,

can you think of any limitation preventing me from upload flac files? While this works fine using the WebUI of Mixcloud,
I always end up with a `concurrent.futures._base.TimeoutError`. Full trace:

`    data = mixcloud.upload(file_path_and_name, show_name)
  File "/home/pi/.local/lib/python3.7/site-packages/aiomixcloud/sync.py", line 55, in sync_method
    return loop.run_until_complete(attribute(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/aiomixcloud/decorators.py", line 174, in wrapper
    return await coroutine(self, *args, params=params, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/aiomixcloud/decorators.py", line 112, in wrapper
    return await coroutine(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/aiomixcloud/core.py", line 412, in upload
    return await self._upload(params, data, url)
  File "/home/pi/.local/lib/python3.7/site-packages/aiomixcloud/core.py", line 387, in _upload
    async with self._session.post(final_url, data=data) as response:
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError`

Tested this on both Debian Buster and Windows 10, same issue- with or without async upload.
I know there is a file limit/ size assertion and I commented that out in the core.py.

Cheers,
J

**Comment by amikrop** [comment]
Hello. I couldn't reproduce (Ubuntu 16.04, Python 3.6.10). Trying to upload [this flac file](https://helpguide.sony.net/high-res/sample1/v1/data/Sample_BeeMoved_96kHz24bit.flac.zip) with the sync version works. What if you try to upload a smaller flac file? Not sure if this error is somehow related to the API not allowing uploads bigger than the size limit (and behaving accordingly). Commenting out the assertion still won't make the API accept uploads bigger than the limit.

**Comment by fa7ecc1f76** [comment]
Thanks for your reply.  The file is around 800 MB, a 2 hour radio show. So uploading a smaller file is no option for me. I can only fall back to mp3 but the idea behind uploading flac is to have a minimum of quality loss during Mixcloud encoding. According to 
https://www.mixcloud.com/developers/#uploads the file should not be larger than 4294967296 bytes. But that are about 4294 MB and not 500 MB. That was the reason I was commenting out the assertion, since it didn't match that limit.

**Comment by amikrop** [comment]
I was suggesting to try uploading a smaller/different flac file to see if the problem persists. As I am not sure why this could be happening, maybe try to take the issue/question to the standard library (concurrent.futures) maintainers?

**Comment by fa7ecc1f76** [comment]
Sorry for ignoring your suggestion. I will do that and let you know. Will also try to post the file with plain Curl.

**Comment by fa7ecc1f76** [comment]
Uploading a 403 MB Flac doesn't complete either. I've seen you updated the file limit in your constant definitions to reflect the Mixcloud API specs.

Will let you know how the Curl POST went.

**Comment by fa7ecc1f76** [comment]
Posting Flac files of size 403 MB and 800 MB with Curl worked fine:

`curl -F mp3=@my.flac \
     -F "name=My Flac" \
     -F "unlisted=true" \
     -F "description=Testing" \
     https://api.mixcloud.com/upload/?access_token=my-token`

**Comment by amikrop** [comment]
I am not sure why this could be happening and flac uploading works for me. You can try to contact the respective standard library module maintainers and find out in which cases a TimeoutError can occur in concurrent.futures.

**Comment by fa7ecc1f76** [comment]
No, I will use Curl then. For what I need this for it's not worth spending more time. Thanks anyway.
