### ISSUE TITLE
Dashboard API Access?

### ISSUE THREAD

**Issue by qwertycody** [amikrop/aiomixcloud#3]
Happened upon the reddit post where this app was posted...

Are you aware of any endpoints with mixcloud where you can query the main homepage that is tailored to the currently logged in user?

Below is an example screenshot of what I'm referring to...

![image](https://user-images.githubusercontent.com/4968312/97238004-c61dd100-17be-11eb-8e9b-70a9a0aba8b5.png)

**Comment by amikrop** [comment]
Looking anew at [their API docs](https://www.mixcloud.com/developers/) I couldn't find any documented endpoint related to this, nor some kind of root endpoint. I tried .get('') and .get('/') receiving an empty dict as a response (while on authorized usage). If you find out anything about it I would be happy to hear.

**Comment by qwertycody** [comment]
I tried the same test calls as well and tried a few different variations of
verbs too for the root.

Went as far as checking network traffic too but no success.

They seem to use mostly GraphQL instead of their own published API so it'd
make sense that a decent chunk of functionality is flat out missing from it.

I have a support ticket in and am seeing if I will have any luck contacting
their dev team and will keep you posted.

Would be nice if they had a forum or discord or something like that.

**Comment by amikrop** [comment]
Yes, it would. Alright then, if you get more news you could open a new issue. Thanks for investigating.
